### ISSUE TITLE
Why are `level.backgrounds.ranges` arrays?

### ISSUE THREAD

**Issue by jacobcarpenter** [meth-meth-method/super-mario#1]
I'm curious why you chose to define `level.background.ranges` as arrays rather than objects with `x1`, `x2`, `y1`, and `y2` properties?

I do like the use of destructuring into named variables in:

```js
background.ranges.forEach(([x1, x2, y1, y2]) => { // ...
```

... but you could still use object destructuring, with the object's properties:

```js
background.ranges.forEach(({ x1, x2, y1, y2 }) => { // ...
```

Enjoyed the video. Thanks!

**Comment by pomle** [comment]
I figured since I'm always going to use the same order I can save a little space and a little typing.

**Comment by jacobcarpenter** [comment]
Yeah.

You could always create a range factory helper to enable creating the objects without having to repeatedly name their properties... but I understand the desire for concise specification.

Thanks!
