### ISSUE TITLE
Unwanted modifiing of the bounding box while collision checking.

### ISSUE THREAD

**Issue by AFE-GmdG** [meth-meth-method/super-mario#10]
https://github.com/meth-meth-method/super-mario/blob/dc5ab340f1aff68f80ee120ee3653fad7b6274d5/public/js/TileCollider.js#L30

also in lines 37, 67 and 74:

You change the bounding box in a collision check. This can't be right.
I solved this error in my typescript Version at https://just-run.it/#/rySrbk86W/7 on File TileCollider.ts

Greetings, Andreas

**Comment by pomle** [comment]
Thanks for the feedback, but it's intended to be like that. 

The `right` property is defined as a "setter" and will update `X`. Could be thought of as `BoundingBox.setPosFromRightSide()`.

I would link to the line of code in your project, but can't figure out how to deeplink into a file over there. Anyway, it's in `BoundingBox` class line 43.
