### ISSUE TITLE
unwanted bounce

### ISSUE THREAD

**Issue by AFE-GmdG** [meth-meth-method/super-mario#11]
https://github.com/meth-meth-method/super-mario/blob/dc5ab340f1aff68f80ee120ee3653fad7b6274d5/public/js/entities/Goomba.js#L25

If you kill goomba by stomping on it you bounce of. Thats the right behavior.
But until the goomba leaves the level (the 2 seconds the flat animation is active) you bounce over and over again - and thats not right.

If you add
us.canCollide = false
to this position it won't happen anymore the dead goomba falls right through the level.

So you have to split up the canCollide property on the Entity class to
- canCollideWithBackground and
- canCollideWithOtherEntity

You have to Update the Level update function:
``` ts
  public update(deltaTime: number) {
    this.entities.forEach(entity => {
      entity.update(deltaTime, this);

      entity.position.x += entity.velocity.x * deltaTime;
      if (entity.canCollideWithBackground) {
        this.tileCollider.checkX(entity);
      }

      entity.position.y += entity.velocity.y * deltaTime;
      if (entity.canCollideWithBackground) {
        this.tileCollider.checkY(entity);
      }

      entity.velocity.y += this.gravity * deltaTime;
    });

    this.entities.forEach(entity => {
      if (entity.canCollideWithOtherEntity) {
        this.entityCollider.check(entity);
      }
    });

    this.totalTime += deltaTime;
  }
```

You have to update the EntityCollider check function:
```ts
  public check(subject: Entity) {
    this.entities.forEach(candidate => {
      if (subject === candidate || !candidate.canCollideWithOtherEntity) {
        return;
      }

      if (subject.boundingBox.overlaps(candidate.boundingBox)) {
        subject.collides(candidate);
        candidate.collides(subject);
      }
    })
  }
```

**Comment by pomle** [comment]
Thanks, but I have another plan for this. The canCollide flag is not really nice to use and having knowledge of background inside the entity is not ideal either.

The plan is to add a little queing function of what will happen to the entity after iteration so that we can sett the dead flag after all updates have been complete. This way there is no race condition between objects inside the update loop.

**Comment by pomle** [comment]
Will be fixed by https://github.com/meth-meth-method/super-mario/pull/13

**Comment by pomle** [comment]
https://github.com/meth-meth-method/super-mario/pull/13 has been merged and is on master. Will be in episode https://github.com/meth-meth-method/super-mario/releases/tag/ep13.
