### ISSUE TITLE
all entity collisions are doubled

### ISSUE THREAD

**Issue by mkrasuski** [meth-meth-method/super-mario#32]
on entity collider we have both `subject.collides(candidate)` and `candidate.collides(subject)` and entity nested loops cause every `subject != candidate` pair go to this. 
As result, on collision, for example `mario.collides(goomba)` is called with `subject === mario` and `candidate == goomba` and then with `subject === goomba` and `candidate === mario`.

With such a loop nesting calling only `subject.collides(candidate)` is enough.

**Comment by pomle** [comment]
Fixed in https://github.com/meth-meth-method/super-mario/commit/ab778dbcda3addf5a1f59956478f3453fe2751b8#diff-1ab87ddb118485cb1607a5f4d6f01820
