### ISSUE TITLE
Unnecesary deltaTime multiplication in Go trait

### ISSUE THREAD

**Issue by Vakrim** [meth-meth-method/super-mario#5]
https://github.com/meth-meth-method/super-mario/blob/3ee49f85f4149aa978bd5cc792ba3bba0b22a8db/public/js/traits/Go.js#L12

If speed is defined in pixels per seconds, there is no need to multiply it by `deltaTime` to set velocity of entity.

And if you are pressing key, you want Mario move with constant velocity.

**Comment by iPG1101** [comment]
That is so that if the framerate is 20, mario will move just as fast as if the framerate was 200. If 1 ms passed (1000fps), move 0.1px (example, probably not that fast), if 100ms (10fps), move 10px

**Comment by pomle** [comment]
I think you are correct. We will rework all movement code in a later episode so will address it then. Thanks for the heads up @Vakrim .

**Comment by pomle** [comment]
Go trait have been refactored so hopefully this doesn't apply anymore.
