### ISSUE TITLE
Will you refactor the main.js?

### ISSUE THREAD

**Issue by eporat** [meth-meth-method/super-mario#6]
Hi, I really love the series so far.
Just a quick question, will you reorganize "main.js"?
Also, should Mario's initial position be in the JSON file for the levels.

I love everything you're doing! It is very interesting to see the code evolve from episode to episode and to look back at previous episodes and see the changes.

- Eitan

**Comment by pomle** [comment]
Yes, everything is subject to refactor. We are continuously cleaning up main as we go. I use main.js as the playground for inserting features for prototyping, and as they mature, I decouple them.

Thanks for your question and input. 

Glad you're following along!
